CREATE TABLE transactions (
                              id           bigint generated by default as identity
                                  primary key,
                              trx_nr VARCHAR(255) constraint uk_trx_transaction_nr
                                  unique,
                              customer_nr VARCHAR(255),
                              is_credit boolean,
                              amount NUMERIC(19,2),
                              date DATE,
                              customer_id BIGINT,
                              CONSTRAINT fk_customer
                                  FOREIGN KEY (customer_id)
                                      REFERENCES customers(id)
                                      ON DELETE CASCADE
);

CREATE INDEX ix_transactions_customer_id ON transactions (customer_id);