create table customers
(
    id           bigint generated by default as identity
        primary key,
    customer_nr  varchar(255)
        constraint uk_customer_customer_nr
            unique,
    first_name   varchar(255),
    last_name    varchar(255),
    email        varchar(255),
    phone_number varchar(255)
);
